config/routes.rb
Rails.application.routes.draw do
  resources :offertes do
    resources :posities
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'offertes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offerte.rb
class Offerte < ApplicationRecord
  has_many :posities
  enum status: [ :nieuw, :uitgebracht, :opdracht, :historisch ]


end

app/models/positie.rb
class Positie < ApplicationRecord
  belongs_to :offerte
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/offertes_controller.rb
class OffertesController < ApplicationController
  before_action :set_offerte, only: [:show, :edit, :update, :destroy]

  # GET /offertes
  # GET /offertes.json
  def index
    @offertes = Offerte.all
  end

  # GET /offertes/1
  # GET /offertes/1.json
  def show
  end

  # GET /offertes/new
  def new
    @offerte = Offerte.new
  end

  # GET /offertes/1/edit
  def edit
  end

  # POST /offertes
  # POST /offertes.json
  def create
    @offerte = Offerte.new(offerte_params)

    respond_to do |format|
      if @offerte.save
        format.html { redirect_to @offerte, notice: 'Offerte was successfully created.' }
        format.json { render :show, status: :created, location: @offerte }
      else
        format.html { render :new }
        format.json { render json: @offerte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offertes/1
  # PATCH/PUT /offertes/1.json
  def update
    respond_to do |format|
      if @offerte.update(offerte_params)
        format.html { redirect_to @offerte, notice: 'Offerte was successfully updated.' }
        format.json { render :show, status: :ok, location: @offerte }
      else
        format.html { render :edit }
        format.json { render json: @offerte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offertes/1
  # DELETE /offertes/1.json
  def destroy
    @offerte.destroy
    respond_to do |format|
      format.html { redirect_to offertes_url, notice: 'Offerte was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offerte
      @offerte = Offerte.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offerte_params
      params.require(:offerte).permit(:projectnaam, :projectnummer, :plaats, :status)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
  end
end

app/controllers/posities_controller.rb
class PositiesController < ApplicationController
  before_action :set_offerte
  before_action :set_positie, only: [:show, :edit, :update, :destroy]

  # GET /posities
  # GET /posities.json
  def index
    @posities = Positie.all
  end

  # GET /posities/1
  # GET /posities/1.json
  def show
  end

  # GET /posities/new
  def new
    @positie = @offerte.posities.new
  end

  # GET /posities/1/edit
  def edit
  end

  # POST /posities
  # POST /posities.json
  def create

    @positie = @offerte.posities.new(positie_params)

    respond_to do |format|
      if @positie.save
        format.html { redirect_to [@offerte, @positie], notice: 'Positie was successfully created.' }
        format.json { render :show, status: :created, location: @positie }
      else
        format.html { render :new }
        format.json { render json: @positie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posities/1
  # PATCH/PUT /posities/1.json
  def update
    respond_to do |format|
      if @positie.update(positie_params)
        format.html { redirect_to @positie, notice: 'Positie was successfully updated.' }
        format.json { render :show, status: :ok, location: @positie }
      else
        format.html { render :edit }
        format.json { render json: @positie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posities/1
  # DELETE /posities/1.json
  def destroy
    @positie.destroy
    respond_to do |format|
      format.html { redirect_to posities_url, notice: 'Positie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_offerte
      @offerte = Offerte.find_by(id: params[:offerte_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_positie
      @positie = Positie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def positie_params
      params.require(:positie).permit(:regel, :fabrikaat, :systeem, :ip, :verdeler, :aantal, :stuksprijs, :offerte_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def addTime(array)

    hh = 0
    mm = 0
    ss = 0
    totalSeconds = 0

    array.each do |item|
      time = item.split(":")
        if time.size > 3
          return "Please format HH:MM:SS"
        end

      hh += time[0].to_i
      mm += time[1].to_i
      ss += time[2].to_i

    end

    totalSeconds = ss + (mm * 60) + (hh * (60 * 60))


    seconds = totalSeconds % 60
    minutes = (totalSeconds / 60) % 60
    hours = totalSeconds / (60 * 60)

    return format("%02d:%02d:%02d", hours, minutes, seconds)

  end
end

app/helpers/offertes_helper.rb
module OffertesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posities_helper.rb
module PositiesHelper
end

app/views/layouts/_navbar.html.erb
<!-- <img src="<%= "#{image_path('gtv.jpg')}" %>" alt="GTV"> -->


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
<img src="<%= "#{image_path('gtv.jpg')}" %>" alt="GTV">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= "#{offertes_path}" %>">Offertes <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Artikelen</a></li>

        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->

      </ul>



      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>

        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->

        <form class="navbar-form navbar-right">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GtvOfferte" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

<%= render 'layouts/navbar' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
    </div>
    
  </body>
</html>

app/views/offertes/_form.html.erb
<%= simple_form_for @offerte, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :projectnummer %>
  <%= f.error_span(:projectnummer) %>

  <%= f.input :projectnaam %>
  <%= f.error_span(:projectnaam) %>
  <%= f.input :plaats %>
  <%= f.error_span(:plaats) %>

  <%= f.input :status %>
  <%= f.error_span(:status) %>

  <%= f.button :submit, 'Maak offerte', :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                offertes_path, :class => 'btn btn-default' %>
  <%= link_to "Posities", offerte_posities_path(@offerte), :class => 'btn btn-info' %>

<% end %>

app/views/offertes/edit.html.erb
<%- model_class = Offerte -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/offertes/index.html.erb
<%- model_class = Offerte -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:projectnaam) %></th>
      <th><%= model_class.human_attribute_name(:projectnummer) %></th>
      <th><%= model_class.human_attribute_name(:plaats) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @offertes.each do |offerte| %>
      <tr>
        <td><%= link_to offerte.id, offerte_path(offerte) %></td>
        <td><%= offerte.projectnaam %></td>
        <td><%= offerte.projectnummer %></td>
        <td><%= offerte.plaats %></td>
        <td><%= offerte.status %></td>
        <td><%=l offerte.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      offerte_path(offerte), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_offerte_path(offerte), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      offerte_path(offerte),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_offerte_path,
            :class => 'btn btn-primary' %>

app/views/offertes/new.html.erb
<div class="page-header">
  <h1>Nieuwe offerte</h1>
</div>
<%= render :partial => 'form' %>

app/views/offertes/show.html.erb
<%- model_class = Offerte -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:projectnaam) %>:</strong></dt>
  <dd><%= @offerte.projectnaam %></dd>
  <dt><strong><%= model_class.human_attribute_name(:projectnummer) %>:</strong></dt>
  <dd><%= @offerte.projectnummer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:plaats) %>:</strong></dt>
  <dd><%= @offerte.plaats %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @offerte.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              offertes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_offerte_path(@offerte), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              offerte_path(@offerte),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/pages/main.html.erb
Hello world

app/views/posities/_form.html.erb
<%= simple_form_for [@offerte, @positie], :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :regel %>
  <%= f.error_span(:regel) %>
  <%= f.input :fabrikaat %>
  <%= f.error_span(:fabrikaat) %>
  <%= f.input :systeem %>
  <%= f.error_span(:systeem) %>
  <%= f.input :ip %>
  <%= f.error_span(:ip) %>
  <%= f.input :verdeler %>
  <%= f.error_span(:verdeler) %>
  <%= f.input :aantal %>
  <%= f.error_span(:aantal) %>
  <%= f.input :stuksprijs %>
  <%= f.error_span(:stuksprijs) %>
  <%= f.association :offerte, label_method: :projectnaam, value_method: :id, include_blank: false %>
  <%= f.error_span(:offerte) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                offerte_posities_path, :class => 'btn btn-default' %>
<% end %>

app/views/posities/edit.html.erb
<%- model_class = Positie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posities/index.html.erb
<%- model_class = Positie -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:regel) %></th>
      <th><%= model_class.human_attribute_name(:fabrikaat) %></th>
      <th><%= model_class.human_attribute_name(:systeem) %></th>
      <th><%= model_class.human_attribute_name(:ip) %></th>
      <th><%= model_class.human_attribute_name(:verdeler) %></th>
      <th><%= model_class.human_attribute_name(:aantal) %></th>
      <th><%= model_class.human_attribute_name(:stuksprijs) %></th>
      <th><%= model_class.human_attribute_name(:offerte_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>

  <tbody>
    <% @posities.each do |positie| %>
      <tr>
        <td><%= positie.id %></td>
        <td><%= positie.regel %></td>
        <td><%= positie.fabrikaat %></td>
        <td><%= positie.systeem %></td>
        <td><%= positie.ip %></td>
        <td><%= positie.verdeler %></td>
        <td><%= positie.aantal %></td>
        <td><%= positie.stuksprijs %></td>
        <td><%= positie.offerte_id %></td>
        <td><%=l positie.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      offerte_positie_path(@offerte, positie), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_offerte_positie_path(@offerte, positie), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      offerte_positie_path(@offerte, positie),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_offerte_positie_path,
            :class => 'btn btn-primary' %>

app/views/posities/new.html.erb
<%- model_class = Positie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posities/show.html.erb
<%- model_class = Positie -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:regel) %>:</strong></dt>
  <dd><%= @positie.regel %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fabrikaat) %>:</strong></dt>
  <dd><%= @positie.fabrikaat %></dd>
  <dt><strong><%= model_class.human_attribute_name(:systeem) %>:</strong></dt>
  <dd><%= @positie.systeem %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ip) %>:</strong></dt>
  <dd><%= @positie.ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:verdeler) %>:</strong></dt>
  <dd><%= @positie.verdeler %></dd>
  <dt><strong><%= model_class.human_attribute_name(:aantal) %>:</strong></dt>
  <dd><%= @positie.aantal %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stuksprijs) %>:</strong></dt>
  <dd><%= @positie.stuksprijs %></dd>
  <dt><strong><%= model_class.human_attribute_name(:offerte_id) %>:</strong></dt>
  <dd><%= @positie.offerte_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              offerte_posities_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_offerte_positie_path(@positie), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              offerte_positie_path(@positie),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>